# Generated by Django 2.2 on 2019-05-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='username',
        ),
    ]
