# Generated by Django 2.2 on 2019-05-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
