# Generated by Django 2.2 on 2019-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_auto_20190509_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to='C:\\Users\\user\\Desktop\\FinalProject\\mywebsite\\static\\media'),
        ),
    ]
