# Generated by Django 2.2 on 2019-05-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_auto_20190509_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to='Cvs/%Y/%M/%D/'),
        ),
    ]
