# Generated by Django 2.2 on 2019-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_auto_20190509_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to='Cvs/%Y/%candidate.name'),
        ),
    ]
