# Generated by Django 2.2 on 2019-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_auto_20190510_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to='Cvs/%Y/{candidate.name}'),
        ),
    ]
