# Generated by Django 2.2 on 2019-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_auto_20190511_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to='Cvs/%Y/{<django.db.models.fields.CharField>}'),
        ),
    ]
