# Generated by Django 2.2 on 2019-05-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_auto_20190511_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to='Cv/%Y/{get_upload_path}'),
        ),
    ]
