# Generated by Django 6.0.2 on 2026-02-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_auto_20190511_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
