# Generated by Django 2.2 on 2019-05-08 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interview',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate'),
        ),
    ]
