# Generated by Django 2.2 on 2019-05-09 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20190509_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
    ]
