# Generated by Django 2.2 on 2019-05-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20190509_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='booked',
            new_name='WrittenExam',
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.CharField(default='Zhang', max_length=50),
        ),
        migrations.AddField(
            model_name='interview',
            name='position',
            field=models.CharField(default='Machine Learning engineer', max_length=50),
        ),
    ]
