# Generated by Django 2.2 on 2019-05-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_auto_20190509_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='WrittenExam',
        ),
    ]
