# Generated by Django 2.2 on 2019-05-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_remove_interview_writtenexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate'),
        ),
    ]
